name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Add your Docker Hub username as a secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Add your Docker Hub password as a secret

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: st125050/mlfinal_pro:latest
