name: CI/CD Pipeline for Streamlit App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t st125050/mlfinalproject:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push st125050/mlfinalproject:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy application to Azure Web App
        uses: azure/webapps-container-deploy@v2
        with:
          app-name: 'st125050stockpriceprediction'
          image: 'st125050/mlfinalproject:latest'
          registry-url: 'https://index.docker.io/v1/'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
